### ISSUE TITLE
Make a note about author in LICENSE

### ISSUE THREAD

**Issue by dan1wang** [nea/Typescript-Starter#1]
The README file should make a note about updating the author's name in LICENSE if someone wants to publish the project.

**Comment by nea** [comment]
Hey @dan1wang 

This is not how you use a License ^^

The LICENSE file is part of my repository and what I provide. It is not to be changed! If someone wants to redistribute, he/she has to license it themselves. My stated LICENSE does not change just because someone changes the name.


Best
